<?php
use App\Product;
use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data =[
          [

            'category_id' => 1,
            'name'=>'iPhone 11 Pro Max',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>2340000,
            'quantity' => 15,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()
        ],

        [

            'category_id' => 1,
            'name'=>'iPhone 6 plus',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>54684000,
            'quantity' => 10,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 1,
            'name'=>'iPhone 7',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>76366855,
            'quantity' => 9,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30', 
            'created_at' =>now()          
        ],
        [

            'category_id' => 1,
            'name'=>'iPhone 8 Plus',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>73758445,
            'quantity' => 11,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30' ,
            'created_at' =>now()          
        ],
        [

            'category_id' => 1,
            'name'=>'iPhone XS Max',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>5884445,
            'quantity' => 14,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 2,
            'name'=>'Sam Sung J2',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>29490000,
            'quantity' => 13,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 2,
            'name'=>'Sam Sung Note 9',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>29490000,
            'quantity' => 11,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 2,
            'name'=>'iPhone X Pro Max',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>29490000,
            'quantity' => 9,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 3,
            'name'=>'OPPO Reno4',

            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>29490000,
            'quantity' => 23,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 3,
            'name'=>'OPPO Reno3',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>29490000,
            'quantity' => 12,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 4,
            'name'=>'Vsmart Active 3',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>29490000,
            'quantity' => 18,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 4,
            'name'=>'Vsmart Active 4',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>29490000,
            'quantity' => 15,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 4,
            'name'=>'Vsmart Joy 3',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>29490000,
            'quantity' => 16,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 4,
            'name'=>'Vsmart Star 3',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>29490000,
            'quantity' => 15,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 5,
            'name'=>'Xiaomi Remi 9A',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>29490000,
            'quantity' => 18,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 5,
            'name'=>'Xiaomi Remi 9C',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>29490000,
            'quantity' => 19,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 6,
            'name'=>'Relme C3i',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>29490000,
            'quantity' => 15,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 6,
            'name'=>'Relme C11',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>29490000,
            'quantity' => 15,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 7,
            'name'=>'Nokia 5.3',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>29490000,
            'quantity' => 15,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 7,
            'name'=>'Nokia C2',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>29490000,
            'quantity' => 13,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 8,
            'name'=>'VIVO Y1S',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>29490000,
            'quantity' => 17,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 8,
            'name'=>'ViVo X50',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>29490000,
            'quantity' => 21,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 9,
            'name'=>'Huawei Y1S',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>29490000,
            'quantity' => 21,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ],
        [

            'category_id' => 9,
            'name'=>'Huawei Y6P',
            'title' => 'iPhone 11 Pro Max 64GB',
            'description' => 'Iphone 11 pro max 64 GB.',
            'price' =>29490000,
            'quantity' => 12,
            'size' => '158.0 x 77.8 x 8.1 mm',
            'weight' => '226 g',
            'color' => 'vàng',
            'image' => '/img/user/abc.png',
            'display'=>'6.5 inchs, Super Retina XDR, 1242 x 2688 Pixels',
            'os' => 'iOS 13',
            'storage' => '64GB',
            'ram' => '4GB',
            'cpu' =>'Apple A13 Bionic 6 nhân',
            'gpu'=> 'Apple GPU 4 nhân',
            'primary_camera' => '12.0 MP',
            'rear_camera'=> '3 camera 12 MP',
            'battery'=> '3969 mAh',
            'warranty'=> '12 tháng',
            'promotion_price' =>27490000,
            'start_promotion' => '2020-04-10',
            'end_promotion' =>'2020-07-30',
            'created_at' =>now()           
        ]
    ];
    Product::insert($data);
}
}
